/**
 * Vite config for @contractor-ops/web-vite.
 *
 * Step 12 hardening:
 *   - manualChunks vendor split (react, trpc, i18n)
 *   - rollup-plugin-visualizer behind ANALYZE=1
 *   - @sentry/vite-plugin when SENTRY_AUTH_TOKEN is set (source-map upload)
 */

import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import react from '@vitejs/plugin-react';
import { visualizer } from 'rollup-plugin-visualizer';
import { defineConfig, loadEnv } from 'vite';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../..');

/**
 * Vendor chunking rules. Order matters — first matching rule wins, so more-specific
 * patterns (react-router, react-i18next, ...) MUST come before the broad `react`
 * bucket. pnpm paths look like `.pnpm/react-router-dom@7/node_modules/react-router-dom/...`,
 * so substrings like `react` appear in many unrelated packages.
 *
 * Goals:
 *   - Keep no single chunk > 500 KB minified.
 *   - Aim for ~10–15 vendor chunks total (HTTP/2 multiplexing vs. cache granularity).
 *   - Lazy-route splitting stays auto-generated by Rollup from dynamic imports.
 */
const VENDOR_RULES = [
  // Local first (not under node_modules): monorepo packages.
  // Locale JSON is split per language in vendorChunker (lazy-loaded).
  { name: 'vendor-ui-kit', test: id => id.includes('@contractor-ops/ui') },
  { name: 'vendor-validators', test: id => id.includes('@contractor-ops/validators') },
  { name: 'vendor-feature-flags', test: id => id.includes('@contractor-ops/feature-flags') },

  // node_modules buckets.
  { name: 'vendor-router', test: id => id.includes('react-router') || id.includes('/nuqs/') },
  {
    name: 'vendor-i18n',
    test: id =>
      id.includes('react-i18next') || id.includes('i18next') || id.includes('intl-messageformat'),
  },
  {
    name: 'vendor-forms',
    test: id =>
      id.includes('react-hook-form') ||
      id.includes('@hookform/') ||
      id.includes('react-day-picker') ||
      id.includes('react-dropzone'),
  },
  {
    name: 'vendor-pdf',
    test: id => id.includes('react-pdf') || id.includes('@react-pdf/') || id.includes('pdfjs-dist'),
  },
  {
    name: 'vendor-charts',
    test: id => id.includes('recharts') || id.includes('/d3-') || id.includes('victory-vendor'),
  },
  { name: 'vendor-dnd', test: id => id.includes('@dnd-kit/') },
  {
    name: 'vendor-motion',
    test: id =>
      id.includes('/motion/') ||
      id.includes('/motion-dom/') ||
      id.includes('/motion-utils/') ||
      id.includes('framer-motion'),
  },
  { name: 'vendor-trpc', test: id => id.includes('@trpc/') || id.includes('@tanstack/') },
  {
    name: 'vendor-sentry',
    test: id => id.includes('@sentry/') || id.includes('@sentry-internal/'),
  },
  { name: 'vendor-validation', test: id => id.includes('/zod/') || id.includes('superjson') },
  { name: 'vendor-icons', test: id => id.includes('lucide-react') || id.includes('react-icons') },
  { name: 'vendor-auth', test: id => id.includes('better-auth') },
  { name: 'vendor-date', test: id => id.includes('date-fns') },
  { name: 'vendor-posthog', test: id => id.includes('posthog-js') },
  { name: 'vendor-utils', test: id => id.includes('es-toolkit') || id.includes('@base-ui/utils') },
  { name: 'vendor-images', test: id => id.includes('/unpic/') || id.includes('@unpic/') },
  { name: 'vendor-logger', test: id => id.includes('@axiomhq/') },
  {
    name: 'vendor-state',
    test: id =>
      id.includes('@reduxjs/toolkit') ||
      id.includes('react-redux') ||
      id.includes('/redux/') ||
      id.includes('reselect') ||
      id.includes('/immer/'),
  },
  {
    name: 'vendor-intl',
    test: id => id.includes('@formatjs/') || id.includes('/use-intl/'),
  },
  {
    name: 'vendor-floating',
    test: id => id.includes('@floating-ui/'),
  },
  {
    name: 'vendor-finance',
    test: id => id.includes('decimal.js') || id.includes('ibantools'),
  },
  // Core React last so it doesn't swallow react-* packages above.
  {
    name: 'vendor-react',
    test: id =>
      id.includes('/react-dom/') ||
      id.includes('/react/') ||
      id.includes('scheduler') ||
      id.includes('use-sync-external-store'),
  },
  {
    name: 'vendor-ui',
    test: id =>
      id.includes('@radix-ui/') ||
      id.includes('clsx') ||
      id.includes('tailwind-merge') ||
      id.includes('sonner'),
  },
];

/** One async chunk per locale JSON — matches dynamic import() in messages.ts. */
function messageChunkName(id) {
  const match = id.match(/web\/messages\/([a-z]{2})\.json/);
  return match ? `vendor-messages-${match[1]}` : 'vendor-messages';
}

/** Resolve a module id to a vendor chunk name, or `undefined` for app code. */
function vendorChunker(id) {
  if (id.includes('web/messages/')) return messageChunkName(id);

  const isLocalMonorepo = id.includes('@contractor-ops/');
  if (!(id.includes('node_modules') || isLocalMonorepo)) return;
  for (const rule of VENDOR_RULES) {
    if (rule.test(id)) return rule.name;
  }
  return id.includes('node_modules') ? 'vendor' : undefined;
}

/** @type {import('vite').PluginOption} */
async function sentryPlugin() {
  if (!process.env.SENTRY_AUTH_TOKEN) return null;
  try {
    const { sentryVitePlugin } = await import('@sentry/vite-plugin');
    return sentryVitePlugin({
      org: process.env.SENTRY_ORG,
      project: process.env.SENTRY_PROJECT,
      authToken: process.env.SENTRY_AUTH_TOKEN,
      telemetry: false,
      // Defense in depth: paired with `build.sourcemap: 'hidden'` below.
      //   - `'hidden'` strips the `//# sourceMappingURL=` reference from emitted JS,
      //      so browsers + DevTools never auto-fetch maps even if they leaked.
      //   - `filesToDeleteAfterUpload` removes the `.map` files from `dist/` after
      //      they have been uploaded to Sentry — Render's static publish then never
      //      ships them. Without this, every release exposed the entire SPA source
      //      tree at `https://app.contractor-ops.com/assets/*.js.map`.
      sourcemaps: {
        filesToDeleteAfterUpload: ['./dist/**/*.map'],
      },
    });
  } catch {
    return null;
  }
}

export default defineConfig(async ({ mode }) => {
  const analyze = process.env.ANALYZE === '1';
  const sentry = await sentryPlugin();
  const env = loadEnv(mode, repoRoot, '');
  const apiUrl = env.VITE_API_URL || 'http://localhost:4000';

  return {
    envDir: repoRoot,
    plugins: [
      react(),
      sentry,
      analyze &&
        visualizer({
          filename: 'dist/stats.html',
          template: 'treemap',
          gzipSize: true,
          brotliSize: true,
        }),
    ].filter(Boolean),

    resolve: {
      alias: {
        // Mirror the legacy `apps/web` tsconfig `@/*` → `src/*` alias so
        // ported tests + components keep their original import paths.
        '@': resolve(dirname(fileURLToPath(import.meta.url)), './src'),
      },
    },

    test: {
      globals: true,
      environment: 'jsdom',
      include: ['src/**/__tests__/**/*.test.{ts,tsx}'],
      setupFiles: ['./src/test/setup.ts'],
    },

    build: {
      target: 'es2022',
      // `'hidden'` emits .map files for the Sentry plugin to upload but omits
      // the `//# sourceMappingURL` reference in JS so a browser never auto-fetches
      // a map even if one slipped into the published `dist/`. The `.map` files
      // are then deleted by `sentryPlugin` post-upload (see below). Source maps
      // would otherwise be public on a static-site deploy and let anyone
      // reconstruct the full SPA source tree.
      sourcemap: 'hidden',
      chunkSizeWarningLimit: 500,
      rollupOptions: {
        output: {
          manualChunks: vendorChunker,
        },
      },
    },

    server: {
      port: 3000,
      strictPort: true,
      // Portal session helpers post to same-origin `/api/portal/*` (Next parity).
      // Fastify serves them at `/portal/*` on apps/api — rewrite strips `/api`.
      // Auth uses `${VITE_API_URL}/api/auth` directly (auth-provider.tsx).
      proxy: {
        '/api/portal': {
          target: apiUrl,
          changeOrigin: true,
          rewrite: path => path.replace(/^\/api/, ''),
        },
      },
    },
    preview: {
      port: 4173,
      strictPort: true,
    },
  };
});
