// packages/validators/src/__tests__/leitweg-id.fixtures.ts
//
// Leitweg-ID test vectors.
//
// Source strategy:
//   - The canonical fixture corpus for Leitweg-IDs is KoSIT's
//     validator-configuration-xrechnung test suite. In environments where
//     that release zip is reachable, extract `<ram:BuyerReference>` nodes
//     with `grep -roE '[0-9]{2,12}(-[A-Z0-9]{0,30})?-[0-9]{2}'`. In this
//     repo we carry ground-truth values derived from the publicly documented
//     spec example `991-33333TEST-33` and from computed round-trips against
//     our ported ISO 7064 MOD 97-10 implementation (see leitweg-id.ts).
//
//   - Invalid fixtures cover every failure category: malformed structure,
//     wrong check digit, too short, too long, bad character.
//
// Round-trip invariant: every entry in LEITWEG_ID_VALID_FIXTURES MUST satisfy
// `leitwegIdSchema.safeParse(value).success === true`. Every entry in
// LEITWEG_ID_INVALID_FIXTURES MUST fail parsing, and entries labelled
// `check_digit_wrong` MUST produce an error message matching /check digit/i.
//
// If the MOD 97-10 port ever drifts from the KoSIT spec, DO NOT mutate these
// fixtures — fix the algorithm. Research doc §Open Questions #1 explicitly
// flags this as an easy-to-get-wrong-silently area.

/**
 * Leitweg-IDs that MUST parse successfully.
 *
 * Generated by round-tripping coarse + fine payloads through
 * `computeLeitwegCheckDigit` (see leitweg-id.ts). The 2-digit suffix is the
 * ISO 7064 MOD 97-10 check over the coarse + fine payload with
 * alphanumerics decomposed to base-10 digits (A→[1,0] … Z→[3,5]).
 *
 * Coverage:
 *   - coarse-only (no fine-address refinement)
 *   - coarse + fine numeric
 *   - coarse + fine alphanumeric (letters at start / middle / end)
 *   - min coarse length (2 digits)
 *   - max coarse length (12 digits)
 *   - max total length close to spec ceiling (46 chars)
 */
export const LEITWEG_ID_VALID_FIXTURES: readonly string[] = [
  '991-33333TEST-33',
  '04011000-1234512345-06',
  '99-92',
  '991-35',
  '9912-44',
  '123456789012-44',
  '04011000-12345-03',
  '991-12345-73',
  '04011-AGENCY-91',
  '123-ABC-12',
  '991-ABCDEFGHIJ-06',
  '04-BONN01-76',
  '123456789012-ABCDEFGHIJKLMNOPQRSTUVWXYZ0123-03',
] as const;

/** Categorised invalid-fixture reasons. */
export type LeitwegIdInvalidReason =
  | 'malformed'
  | 'check_digit_wrong'
  | 'too_short'
  | 'too_long'
  | 'bad_char';

/**
 * Leitweg-IDs that MUST fail parsing. Each carries its reason category so the
 * test suite can assert the right error pathway.
 */
export const LEITWEG_ID_INVALID_FIXTURES: readonly {
  readonly value: string;
  readonly reason: LeitwegIdInvalidReason;
}[] = [
  // check_digit_wrong — structure OK but last two digits don't match payload
  { value: '991-33333TEST-99', reason: 'check_digit_wrong' },
  { value: '04011000-12345-99', reason: 'check_digit_wrong' },
  { value: '04011-AGENCY-00', reason: 'check_digit_wrong' },
  { value: '991-42', reason: 'check_digit_wrong' },
  { value: '99-12', reason: 'check_digit_wrong' },
  // too_short — coarse must be at least 2 digits; total must be ≥5
  { value: '9-42', reason: 'too_short' },
  { value: '1-1', reason: 'too_short' },
  // too_long — total exceeds 46 chars
  {
    value: '123456789012-ABCDEFGHIJKLMNOPQRSTUVWXYZ01234-42',
    reason: 'too_long',
  },
  // bad_char — lowercase letters not allowed
  { value: '991-agency-42', reason: 'bad_char' },
  { value: '991-mixed#-42', reason: 'bad_char' },
  // malformed — missing hyphen, missing check digit, non-digit coarse
  { value: '99133333TEST63', reason: 'malformed' },
  { value: '991-33333TEST', reason: 'malformed' },
  { value: 'AB-33333TEST-42', reason: 'malformed' },
] as const;
