import type { ReactElement, ReactNode } from 'react';
import { describe, expect, it } from 'vitest';

import type { GdprPrivacyNoticeTemplateProps } from '../gdpr-privacy-notice.js';
import { GdprPrivacyNoticeTemplate } from '../gdpr-privacy-notice.js';

// ---------------------------------------------------------------------------
// Helper — walk the React tree to extract text strings (same approach as
// ir35-sds tests; avoids PDF binary rendering for content assertions).
// ---------------------------------------------------------------------------

function collectText(node: ReactNode): string[] {
  const out: string[] = [];
  function walk(n: ReactNode): void {
    if (n == null || typeof n === 'boolean') return;
    if (typeof n === 'string') {
      out.push(n);
      return;
    }
    if (typeof n === 'number') {
      out.push(String(n));
      return;
    }
    if (Array.isArray(n)) {
      for (const c of n) walk(c);
      return;
    }
    if (typeof n === 'object' && 'props' in (n as object)) {
      const el = n as ReactElement<{ children?: ReactNode; render?: unknown }>;
      walk(el.props.children);
    }
  }
  walk(node);
  return out;
}

function renderText(props: GdprPrivacyNoticeTemplateProps): string {
  const element = GdprPrivacyNoticeTemplate(props);
  return collectText(element).join(' ');
}

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

const ORG_GB = { name: 'Acme Ltd', countryCode: 'GB' };
const ORG_DE = { name: 'Beratung GmbH', countryCode: 'DE' };
const ORG_EU = { name: 'EU Corp', countryCode: 'NL' };
const ORG_MINIMAL = { name: 'NoCountry Inc', countryCode: null };

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('GdprPrivacyNoticeTemplate', () => {
  describe('GB jurisdiction', () => {
    it('renders English "Privacy Notice" title and org name', () => {
      const text = renderText({ jurisdiction: 'GB', organization: ORG_GB });

      expect(text).toContain('Privacy Notice');
      expect(text).toContain('Acme Ltd');
      expect(text).toContain('GB');
    });

    it('renders legal reference from gbPrivacyNotice', () => {
      const text = renderText({ jurisdiction: 'GB', organization: ORG_GB });

      // GB notice references UK GDPR
      expect(text).toMatch(/UK\s*GDPR|Data Protection Act/i);
    });
  });

  describe('DE jurisdiction', () => {
    it('renders German "Datenschutzerklarung" title', () => {
      const text = renderText({ jurisdiction: 'DE', organization: ORG_DE });

      expect(text).toContain('Datenschutzerklärung');
      expect(text).toContain('Beratung GmbH');
    });

    it('renders legal reference from dePrivacyNotice', () => {
      const text = renderText({ jurisdiction: 'DE', organization: ORG_DE });

      // DE notice references DSGVO / BDSG
      expect(text).toMatch(/DSGVO|BDSG|Datenschutz/i);
    });
  });

  describe('EU jurisdiction', () => {
    it('renders English "Privacy Notice" title for EU', () => {
      const text = renderText({ jurisdiction: 'EU', organization: ORG_EU });

      expect(text).toContain('Privacy Notice');
      expect(text).toContain('EU Corp');
    });

    it('renders legal reference from euPrivacyNotice', () => {
      const text = renderText({ jurisdiction: 'EU', organization: ORG_EU });

      // EU notice references GDPR
      expect(text).toMatch(/GDPR|General Data Protection/i);
    });
  });

  describe('edge cases', () => {
    it('renders fallback text for unsupported jurisdiction', () => {
      // Force an unsupported jurisdiction to test the null-notice branch
      const text = renderText({
        jurisdiction: 'AE' as 'GB',
        organization: ORG_MINIMAL,
      });

      expect(text).toContain('Privacy Notice');
      expect(text).toContain('No privacy notice template is available');
    });

    it('handles organization with null countryCode', () => {
      const text = renderText({ jurisdiction: 'GB', organization: ORG_MINIMAL });

      expect(text).toContain('NoCountry Inc');
      // The subtitle should not contain the org country code separator
      // when countryCode is null (though the footer " · " for date is expected).
      expect(text).not.toMatch(/NoCountry Inc\s+·/);
    });

    it('renders Generated by Contractor Ops footer', () => {
      const text = renderText({ jurisdiction: 'GB', organization: ORG_GB });

      expect(text).toContain('Generated by Contractor Ops');
    });

    it('accepts optional locale parameter', () => {
      // Should not throw when locale is explicitly passed
      const text = renderText({
        jurisdiction: 'DE',
        organization: ORG_DE,
        locale: 'de-DE',
      });

      expect(text).toContain('Datenschutzerklärung');
    });
  });
});
