#!/usr/bin/env tsx
/**
 * Generate TypeScript types for next-intl messages from the canonical
 * `apps/web/messages/en.json`. Output is deterministic — re-running with
 * an unchanged source produces a byte-identical file so turbo caches it
 * cleanly.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HEADER = `// AUTO-GENERATED by scripts/generate-i18n-types.ts — do not edit.
// Source: apps/web/messages/en.json
// Run \`pnpm i18n:types\` to regenerate.
`;

type JsonValue =
  | string
  | number
  | boolean
  | null
  | JsonValue[]
  | { [key: string]: JsonValue };

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, '..');
const SOURCE = resolve(REPO_ROOT, 'apps/web/messages/en.json');
const OUTPUT = resolve(REPO_ROOT, 'apps/web/src/generated/i18n/messages.d.ts');

function isObject(value: JsonValue): value is { [key: string]: JsonValue } {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function quoteIdent(key: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
}

function emit(value: JsonValue, indent: number): string {
  if (!isObject(value)) {
    return 'string';
  }
  const pad = '  '.repeat(indent);
  const inner = '  '.repeat(indent + 1);
  const keys = Object.keys(value).sort();
  if (keys.length === 0) {
    return '{}';
  }
  const lines = keys.map((key) => {
    const child = value[key];
    return `${inner}${quoteIdent(key)}: ${emit(child, indent + 1)};`;
  });
  return `{\n${lines.join('\n')}\n${pad}}`;
}

function main(): void {
  const raw = readFileSync(SOURCE, 'utf8');
  const data = JSON.parse(raw) as JsonValue;
  if (!isObject(data)) {
    throw new Error(`Expected ${SOURCE} to be a JSON object`);
  }
  const body = emit(data, 0);
  const output = `${HEADER}\nexport type Messages = ${body};\n`;
  mkdirSync(dirname(OUTPUT), { recursive: true });
  writeFileSync(OUTPUT, output, 'utf8');
  process.stdout.write(`Wrote ${OUTPUT}\n`);
}

main();
