// This file is auto-generated by `payload generate:importmap`.
// The Payload admin runtime regenerates it on startup when collections,
// fields, or admin components change. The committed copy is a no-op fallback
// so the app builds before the first dev run materializes the real map.

export const importMap = {};
