# ─────────────────────────────────────────────────────────────────────────────
# Aurora PostgreSQL Serverless v2 — matches Prisma 7 + Better Auth schema
# that the app already uses on Neon. Engine version must support the same
# SQL features / extensions (uuid-ossp, pgcrypto, citext, etc.).
#
# Serverless v2 scales in 0.5 ACU increments (≈1GB RAM each). Dev/staging
# idles at 0.5 ACU (~$43/mo); prod scales up under load and charges only for
# actual ACU-seconds.
#
# Master password is generated by Terraform and stored in Secrets Manager —
# it is NEVER emitted to logs or the state file in plaintext (random_password
# marks it sensitive). Rotate after bootstrap via Secrets Manager rotation.
# ─────────────────────────────────────────────────────────────────────────────

resource "random_password" "db_master" {
  length  = 48
  special = true
  # Exclude characters that Aurora rejects in master passwords.
  override_special = "!#$%&*()-_+[]{}<>:?"
}

resource "aws_secretsmanager_secret" "db_master" {
  name                    = "${local.name_prefix}-db-master"
  description             = "Aurora master credentials for the ME stack. Rotated manually via Secrets Manager."
  recovery_window_in_days = 30
}

resource "aws_secretsmanager_secret_version" "db_master" {
  secret_id = aws_secretsmanager_secret.db_master.id
  secret_string = jsonencode({
    username = var.db_master_username
    password = random_password.db_master.result
  })
}

module "aurora" {
  source  = "terraform-aws-modules/rds-aurora/aws"
  version = "~> 9.10"

  name              = "${local.name_prefix}-aurora"
  engine            = "aurora-postgresql"
  engine_mode       = "provisioned"  # Serverless v2 uses provisioned mode + serverless-v2 scaling config
  engine_version    = "16.4"         # Latest LTS at time of writing — bump after reviewing upgrade notes
  database_name     = var.db_name
  master_username   = var.db_master_username
  master_password   = random_password.db_master.result
  manage_master_user_password = false  # we manage the secret ourselves

  vpc_id                 = module.vpc.vpc_id
  db_subnet_group_name   = module.vpc.database_subnet_group_name
  create_security_group  = false
  vpc_security_group_ids = [aws_security_group.rds.id]

  serverlessv2_scaling_configuration = {
    min_capacity = var.db_min_capacity
    max_capacity = var.db_max_capacity
  }

  instance_class = "db.serverless"
  instances = {
    primary = {}
    replica = {}
  }

  storage_encrypted    = true
  apply_immediately    = false  # apply changes in next maintenance window
  skip_final_snapshot  = false
  deletion_protection  = var.db_deletion_protection

  backup_retention_period = var.db_backup_retention_days
  preferred_backup_window = "02:00-03:00"  # UTC — 05:00-06:00 Bahrain local (off-peak)
  preferred_maintenance_window = "sun:03:30-sun:04:30"

  # Export Postgres logs to CloudWatch for auditability.
  enabled_cloudwatch_logs_exports = ["postgresql"]

  # Performance Insights for query-level diagnostics. Free tier: 7-day retention.
  performance_insights_enabled          = true
  performance_insights_retention_period = 7
}

# ── DATABASE_URL secret — consumed by ECS task definitions ────────────────
# Separate secret from the raw credentials so we can format the libpq URL
# once and let all 3 tasks reference the same ARN.
resource "aws_secretsmanager_secret" "database_url" {
  name                    = "${local.name_prefix}-database-url"
  description             = "Postgres connection URL for the ME stack. Consumed by ECS tasks via `secrets` block in the task definition."
  recovery_window_in_days = 30
}

resource "aws_secretsmanager_secret_version" "database_url" {
  secret_id = aws_secretsmanager_secret.database_url.id
  secret_string = format(
    "postgresql://%s:%s@%s:5432/%s?sslmode=require",
    var.db_master_username,
    random_password.db_master.result,
    module.aurora.cluster_endpoint,
    var.db_name,
  )
}
