/**
 * scripts/seed-qa-fixtures.ts — deterministic walk-and-fix fixtures.
 *
 * Adds three known-credential identities to the `qa-default-org`:
 *
 *   - QA_ADMIN (Better Auth credential, `admin` member)
 *   - QA_ACCOUNTANT (Better Auth credential, `external_accountant` member)
 *   - QA_CONTRACTOR (existing seeded contractor whose email is rewritten to a
 *     known value, plus a long-lived PortalMagicToken so the walk can trade
 *     the token for a portal session cookie via `/portal/login/verify`).
 *
 * Credentials are persisted to the repo-root `.env` inside a marked block
 * (`# === QA walk fixtures ===` … `# === /QA walk fixtures ===`) so the walk
 * orchestrator can read them without parsing the seed log. The block is
 * regenerated on each invocation; other `.env` lines are preserved.
 *
 * Invoked from `seed-dev.ts` when `--profile=qa` and a qa-default-org row
 * exists in at least one regional DB.
 */

import { createHash, randomBytes } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Logger } from '@contractor-ops/logger';
import { hashPassword } from 'better-auth/crypto';

import type { PrismaClient } from '../src/generated/prisma/client/client.js';

const here = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT_ENV_PATH = resolve(here, '../../../.env');

/** PortalMagicToken expiry for the QA walker. 30 days is long enough to span
 * many walk iterations on a single seed without needing a re-seed solely
 * for token refresh. The token is still single-use; consuming it costs the
 * walk one HTTP round-trip per session lifetime (7 days). */
const PORTAL_TOKEN_TTL_MS = 30 * 24 * 60 * 60 * 1000;

const ENV_BLOCK_START = '# === QA walk fixtures (auto-generated by seed-dev --profile=qa) ===';
const ENV_BLOCK_END = '# === /QA walk fixtures ===';

interface QaOrgIds {
  defaultOrgId: string | null;
  emptyOrgId: string | null;
  stressOrgId: string | null;
}

interface QaFixtureCredentials {
  adminEmail: string;
  adminPassword: string;
  accountantEmail: string;
  accountantPassword: string;
  contractorEmail: string;
  /** PortalMagicToken raw value — pass to `/portal/login/verify?token=…`. */
  contractorPortalToken: string;
  /** Single-org contractor needs a known QA_CONTRACTOR_PASSWORD slot only
   * for documentation parity. The portal flow uses the token above. */
  contractorPassword: string;
  defaultOrgId: string;
  emptyOrgId: string | null;
  stressOrgId: string | null;
}

function generatePassword(): string {
  // 24-byte base64url → ~32 chars, URL-safe, no quoting headaches in .env.
  return randomBytes(24).toString('base64url');
}

function generatePortalToken(): { rawToken: string; hashedToken: string } {
  const rawToken = randomBytes(32).toString('base64url');
  const hashedToken = createHash('sha256').update(rawToken).digest('hex');
  return { rawToken, hashedToken };
}

/**
 * Find the three QA-profile organizations in the supplied region client by
 * the `profile` discriminator stored in `Organization.metadata`. Returns
 * nulls for any org that isn't found (the empty / stress orgs are optional
 * if a future variant trims the qa profile).
 */
async function findQaOrgIds(prisma: PrismaClient): Promise<QaOrgIds> {
  // `metadata` is JSON-as-string; match via raw `LIKE` to avoid pulling
  // every Organization row into memory.
  const rows = await prisma.organization.findMany({
    where: {
      OR: [
        { metadata: { contains: '"profile":"qa-default-org"' } },
        { metadata: { contains: '"profile":"qa-empty-org"' } },
        { metadata: { contains: '"profile":"qa-stress-org"' } },
      ],
    },
    select: { id: true, metadata: true },
  });

  const ids: QaOrgIds = { defaultOrgId: null, emptyOrgId: null, stressOrgId: null };
  for (const row of rows) {
    const metadata = row.metadata ?? '';
    if (metadata.includes('"profile":"qa-default-org"')) ids.defaultOrgId = row.id;
    if (metadata.includes('"profile":"qa-empty-org"')) ids.emptyOrgId = row.id;
    if (metadata.includes('"profile":"qa-stress-org"')) ids.stressOrgId = row.id;
  }
  return ids;
}

interface SeedCredentialUserOpts {
  prisma: PrismaClient;
  organizationId: string;
  email: string;
  passwordHash: string;
  displayName: string;
  memberRole: string;
}

async function seedCredentialUser(opts: SeedCredentialUserOpts): Promise<{ userId: string }> {
  const { prisma, organizationId, email, passwordHash, displayName, memberRole } = opts;

  // Idempotent on email (User.email is `@unique`). On re-seed after a wipe
  // the user is recreated; on a `--append` run we update the password hash
  // so the .env password actually works.
  const existing = await prisma.user.findUnique({ where: { email } });
  let userId: string;
  if (existing) {
    userId = existing.id;
    await prisma.account.updateMany({
      where: { userId, providerId: 'credential' },
      data: { password: passwordHash },
    });
    if (existing.name !== displayName) {
      await prisma.user.update({
        where: { id: userId },
        data: { name: displayName },
      });
    }
  } else {
    const created = await prisma.user.create({
      data: {
        name: displayName,
        email,
        emailVerified: true,
        accounts: {
          create: {
            accountId: email,
            providerId: 'credential',
            password: passwordHash,
          },
        },
      },
      select: { id: true },
    });
    userId = created.id;
  }

  // Member: ensure (org, user) link exists with the requested role.
  const existingMember = await prisma.member.findFirst({
    where: { organizationId, userId },
    select: { id: true, role: true },
  });
  if (existingMember) {
    if (existingMember.role !== memberRole) {
      await prisma.member.update({
        where: { id: existingMember.id },
        data: { role: memberRole },
      });
    }
  } else {
    await prisma.member.create({
      data: { organizationId, userId, role: memberRole },
    });
  }

  return { userId };
}

interface SeedPortalContractorOpts {
  prisma: PrismaClient;
  organizationId: string;
  email: string;
  log: Logger;
}

interface PortalContractorResult {
  contractorId: string;
  rawToken: string;
}

async function seedPortalContractor(
  opts: SeedPortalContractorOpts,
): Promise<PortalContractorResult | null> {
  const { prisma, organizationId, email, log } = opts;

  // Reuse the first ACTIVE contractor we already seeded so we don't have to
  // carry the full Contractor-creation payload here. Rewrite its email to
  // the deterministic QA address — that's how the magic-link lookup finds it.
  const contractor = await prisma.contractor.findFirst({
    where: {
      organizationId,
      status: 'ACTIVE',
      deletedAt: null,
    },
    orderBy: { createdAt: 'asc' },
    select: { id: true, email: true },
  });

  if (!contractor) {
    log.warn(
      { organizationId },
      'qa-default-org has no contractor — skipping portal fixture (run with a non-empty profile to populate)',
    );
    return null;
  }

  if (contractor.email !== email) {
    await prisma.contractor.update({
      where: { id: contractor.id },
      data: { email },
    });
  }

  // Wipe any prior PortalMagicToken row for this email so the walk always
  // consumes the newest token (older rows may have been used already).
  await prisma.portalMagicToken.deleteMany({ where: { email } });

  const { rawToken, hashedToken } = generatePortalToken();
  await prisma.portalMagicToken.create({
    data: {
      email,
      token: hashedToken,
      expiresAt: new Date(Date.now() + PORTAL_TOKEN_TTL_MS),
    },
  });

  return { contractorId: contractor.id, rawToken };
}

/**
 * Replace (or append) the QA-fixture block inside `.env`. Other lines are
 * preserved verbatim. A single trailing newline is enforced after the block.
 */
async function persistEnvFile(values: Record<string, string>): Promise<void> {
  let existing = '';
  try {
    existing = await readFile(REPO_ROOT_ENV_PATH, 'utf8');
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err;
  }

  // Strip any existing fixture block (idempotent re-runs).
  const startIdx = existing.indexOf(ENV_BLOCK_START);
  if (startIdx !== -1) {
    const endIdx = existing.indexOf(ENV_BLOCK_END, startIdx);
    if (endIdx === -1) {
      throw new Error(
        '.env contains the QA fixtures start marker without the closing marker — refusing to overwrite. Edit the file manually first.',
      );
    }
    const afterEnd = existing.indexOf('\n', endIdx) + 1;
    existing = `${existing.slice(0, startIdx)}${existing.slice(afterEnd > 0 ? afterEnd : endIdx + ENV_BLOCK_END.length)}`;
  }

  const lines = [ENV_BLOCK_START];
  for (const [key, value] of Object.entries(values)) {
    lines.push(`${key}=${value}`);
  }
  lines.push(ENV_BLOCK_END);
  const block = `${lines.join('\n')}\n`;

  const trimmed = existing.endsWith('\n') || existing.length === 0 ? existing : `${existing}\n`;
  const next = `${trimmed}${trimmed.length > 0 && !trimmed.endsWith('\n\n') ? '\n' : ''}${block}`;
  await writeFile(REPO_ROOT_ENV_PATH, next, 'utf8');
}

/**
 * Public entrypoint. Returns `null` if no qa-default-org exists in this
 * client (caller may then try the next region's client).
 */
export async function seedQaFixtureUsers(
  prisma: PrismaClient,
  log: Logger,
): Promise<QaFixtureCredentials | null> {
  const ids = await findQaOrgIds(prisma);
  if (!ids.defaultOrgId) return null;

  const adminEmail = process.env.QA_ADMIN_EMAIL ?? 'qa-admin@seed.local';
  const accountantEmail = process.env.QA_ACCOUNTANT_EMAIL ?? 'qa-accountant@seed.local';
  const contractorEmail = process.env.QA_CONTRACTOR_EMAIL ?? 'qa-contractor@seed.local';

  const adminPassword = process.env.QA_ADMIN_PASSWORD ?? generatePassword();
  const accountantPassword = process.env.QA_ACCOUNTANT_PASSWORD ?? generatePassword();
  const contractorPassword = process.env.QA_CONTRACTOR_PASSWORD ?? generatePassword();

  const [adminHash, accountantHash] = await Promise.all([
    hashPassword(adminPassword),
    hashPassword(accountantPassword),
  ]);

  await seedCredentialUser({
    prisma,
    organizationId: ids.defaultOrgId,
    email: adminEmail,
    passwordHash: adminHash,
    displayName: 'QA Admin',
    memberRole: 'admin',
  });

  await seedCredentialUser({
    prisma,
    organizationId: ids.defaultOrgId,
    email: accountantEmail,
    passwordHash: accountantHash,
    displayName: 'QA Accountant',
    memberRole: 'external_accountant',
  });

  const portal = await seedPortalContractor({
    prisma,
    organizationId: ids.defaultOrgId,
    email: contractorEmail,
    log,
  });
  const portalToken = portal?.rawToken ?? '';

  const env: Record<string, string> = {
    QA_ADMIN_EMAIL: adminEmail,
    QA_ADMIN_PASSWORD: adminPassword,
    QA_ACCOUNTANT_EMAIL: accountantEmail,
    QA_ACCOUNTANT_PASSWORD: accountantPassword,
    QA_CONTRACTOR_EMAIL: contractorEmail,
    QA_CONTRACTOR_PASSWORD: contractorPassword,
    QA_CONTRACTOR_PORTAL_TOKEN: portalToken,
    QA_DEFAULT_ORG_ID: ids.defaultOrgId,
  };
  if (ids.emptyOrgId) env.QA_EMPTY_ORG_ID = ids.emptyOrgId;
  if (ids.stressOrgId) env.QA_STRESS_ORG_ID = ids.stressOrgId;

  await persistEnvFile(env);

  log.info(
    {
      defaultOrgId: ids.defaultOrgId,
      emptyOrgId: ids.emptyOrgId,
      stressOrgId: ids.stressOrgId,
      adminEmail,
      accountantEmail,
      contractorEmail,
      portalTokenIssued: portalToken.length > 0,
    },
    'qa fixtures seeded — credentials written to .env (QA_* block)',
  );

  return {
    adminEmail,
    adminPassword,
    accountantEmail,
    accountantPassword,
    contractorEmail,
    contractorPortalToken: portalToken,
    contractorPassword,
    defaultOrgId: ids.defaultOrgId,
    emptyOrgId: ids.emptyOrgId,
    stressOrgId: ids.stressOrgId,
  };
}
