import type { PrivacyNoticeStructured, SupportedJurisdiction } from '@contractor-ops/validators';
import { dePrivacyNotice, euPrivacyNotice, gbPrivacyNotice } from '@contractor-ops/validators';
import type { DocumentProps } from '@react-pdf/renderer';
import { Document, Page, StyleSheet, Text, View } from '@react-pdf/renderer';

export interface GdprPrivacyNoticeTemplateProps {
  jurisdiction: 'GB' | 'DE' | 'EU';
  organization: {
    name: string;
    countryCode: string | null;
  };
  locale?: string;
}

// Phase 56 · Plan 07 — React-PDF template rendered by
// `legal.generatePrivacyNoticePdf`. Sources the SAME {gb,de,eu}PrivacyNotice
// data objects from `@contractor-ops/validators` that the CMS legal
// collection seeds from, so MDX / PDF / DB default content can never
// diverge. UI-SPEC §Interaction 10 — A4, 20mm margins, Helvetica, grayscale
// with a single teal accent on the title.

const TEAL_ACCENT = '#0d7f72';
const GREY_BODY = '#1f2937';
const GREY_MUTED = '#6b7280';
const GREY_RULE = '#d1d5db';

const renderPageNumber = ({ pageNumber, totalPages }: { pageNumber: number; totalPages: number }) =>
  `${pageNumber} / ${totalPages}`;

const styles = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    fontSize: 10,
    lineHeight: 1.5,
    color: GREY_BODY,
    padding: 56,
    paddingBottom: 72,
  },
  header: {
    marginBottom: 24,
    borderBottom: `1px solid ${GREY_RULE}`,
    paddingBottom: 12,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: TEAL_ACCENT,
    marginBottom: 4,
  },
  subtitle: { fontSize: 9, color: GREY_MUTED },
  versionLine: { fontSize: 9, color: GREY_MUTED, marginTop: 4 },
  section: { marginTop: 16 },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: GREY_BODY,
    marginBottom: 6,
  },
  sectionBody: { fontSize: 10, color: GREY_BODY, lineHeight: 1.55 },
  footer: {
    position: 'absolute',
    bottom: 36,
    left: 56,
    right: 56,
    fontSize: 8,
    color: GREY_MUTED,
    textAlign: 'center',
    borderTop: `1px solid ${GREY_RULE}`,
    paddingTop: 8,
  },
  pageNumber: {
    position: 'absolute',
    bottom: 36,
    right: 56,
    fontSize: 8,
    color: GREY_MUTED,
  },
});

function selectNotice(jurisdiction: SupportedJurisdiction): PrivacyNoticeStructured | null {
  if (jurisdiction === 'GB') return gbPrivacyNotice;
  if (jurisdiction === 'DE') return dePrivacyNotice;
  if (jurisdiction === 'EU') return euPrivacyNotice;
  return null;
}

function titleForJurisdiction(jurisdiction: 'GB' | 'DE' | 'EU'): string {
  if (jurisdiction === 'DE') return 'Datenschutzerklärung';
  return 'Privacy Notice';
}

export function GdprPrivacyNoticeTemplate({
  jurisdiction,
  organization,
  locale,
}: GdprPrivacyNoticeTemplateProps) {
  const notice = selectNotice(jurisdiction);
  const title = titleForJurisdiction(jurisdiction);
  const documentProps: DocumentProps = {
    title: `${title} — ${organization.name}`,
    author: 'Contractor Ops',
    subject: title,
    language: locale ?? (jurisdiction === 'DE' ? 'de' : 'en'),
  };

  if (!notice) {
    return (
      <Document {...documentProps}>
        <Page size="A4" style={styles.page}>
          <Text style={styles.title}>{title}</Text>
          <Text style={styles.sectionBody}>
            No privacy notice template is available for jurisdiction '{jurisdiction}'.
          </Text>
        </Page>
      </Document>
    );
  }

  return (
    <Document {...documentProps}>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{title}</Text>
          <Text style={styles.subtitle}>
            {organization.name}
            {organization.countryCode ? ` · ${organization.countryCode}` : ''}
          </Text>
          <Text style={styles.versionLine}>{notice.legalReference}</Text>
        </View>

        {notice.sections.map(section => (
          <View key={section.title} style={styles.section} wrap={false}>
            <Text style={styles.sectionTitle}>{section.title}</Text>
            <Text style={styles.sectionBody}>{section.content}</Text>
          </View>
        ))}

        <Text style={styles.footer} fixed>
          Generated by Contractor Ops · {new Date().toISOString().split('T')[0]}
        </Text>
        <Text style={styles.pageNumber} render={renderPageNumber} fixed />
      </Page>
    </Document>
  );
}
